/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
//import jdk.nashorn.internal.objects.NativeJavaImporter;

/**
 *
 * @author 51930
 */
public class farma extends javax.swing.JFrame {

    /**
     * Creates new form farma
     */
    public farma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        chbAmox = new javax.swing.JCheckBox();
        lblAmox = new javax.swing.JLabel();
        CAmox = new javax.swing.JTextField();
        SAmox = new javax.swing.JTextField();
        lblIbu = new javax.swing.JLabel();
        CIbu = new javax.swing.JTextField();
        SIbu = new javax.swing.JTextField();
        CAnta = new javax.swing.JTextField();
        SAnta = new javax.swing.JTextField();
        chbIbu = new javax.swing.JCheckBox();
        chbAnta = new javax.swing.JCheckBox();
        lblAnta = new javax.swing.JLabel();
        lblPeni = new javax.swing.JLabel();
        CPeni = new javax.swing.JTextField();
        SPeni = new javax.swing.JTextField();
        chbPeni = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        timporte = new javax.swing.JTextField();
        descuento = new javax.swing.JTextField();
        tpagar = new javax.swing.JTextField();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        chbAmox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chbAmox.setText("Amoxicilina 500Mg.");
        chbAmox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbAmoxActionPerformed(evt);
            }
        });

        lblAmox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAmox.setText("80.00");

        CAmox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAmoxActionPerformed(evt);
            }
        });
        CAmox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CAmoxKeyReleased(evt);
            }
        });

        SAmox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAmoxActionPerformed(evt);
            }
        });
        SAmox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SAmoxKeyReleased(evt);
            }
        });

        lblIbu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblIbu.setText("50.00");

        CIbu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CIbuKeyReleased(evt);
            }
        });

        SIbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIbuActionPerformed(evt);
            }
        });

        CAnta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CAntaKeyReleased(evt);
            }
        });

        SAnta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAntaActionPerformed(evt);
            }
        });

        chbIbu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chbIbu.setText("Ibuprofeno 125 Mg.");
        chbIbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIbuActionPerformed(evt);
            }
        });

        chbAnta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chbAnta.setText("Antalgia 100 Mg.");
        chbAnta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbAntaActionPerformed(evt);
            }
        });

        lblAnta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAnta.setText("65.00");

        lblPeni.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPeni.setText("40.00");

        CPeni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CPeniKeyReleased(evt);
            }
        });

        SPeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPeniActionPerformed(evt);
            }
        });

        chbPeni.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chbPeni.setText("Penicilina 1000 gr.");
        chbPeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbPeniActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Sub Total");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Pre_Unitario");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Cantidad");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("S/N");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Descripción");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbIbu)
                    .addComponent(chbPeni)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel10))
                        .addComponent(chbAmox))
                    .addComponent(chbAnta))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIbu)
                            .addComponent(lblAmox)
                            .addComponent(lblPeni)
                            .addComponent(lblAnta))
                        .addGap(86, 86, 86)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CAmox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CIbu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CAnta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addComponent(CPeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SAnta, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                        .addComponent(SIbu)
                        .addComponent(SAmox)
                        .addComponent(SPeni)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbAmox)
                    .addComponent(CAmox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SAmox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbIbu)
                    .addComponent(lblIbu)
                    .addComponent(CIbu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SIbu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnta)
                    .addComponent(CAnta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbAnta)
                    .addComponent(SAnta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPeni)
                    .addComponent(chbPeni)
                    .addComponent(SPeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        btnCalcular.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calcular 48.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setContentAreaFilled(false);
        btnCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalcular.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calcular 48.png"))); // NOI18N
        btnCalcular.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calcular 64.png"))); // NOI18N
        btnCalcular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo 48.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo 48.png"))); // NOI18N
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo 64.png"))); // NOI18N
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir48.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setContentAreaFilled(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir48.png"))); // NOI18N
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir 64.png"))); // NOI18N
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addGap(28, 28, 28)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setText("FACTURA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(204, 204, 204))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Totales y Descuentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Importe Parcial:   S/.");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Descuento:          S/.");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Total a Pagar:      S/.");

        descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descuentoActionPerformed(evt);
            }
        });
        descuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descuentoKeyReleased(evt);
            }
        });

        tpagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpagarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descuento, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(tpagar)
                    .addComponent(timporte))
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(timporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tpagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SAmoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAmoxActionPerformed
       
    }//GEN-LAST:event_SAmoxActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
       //Desabilitar los checkbox al momento de presionar el boton cacular si no se marco la opcion
       //Si las cajas de texto no se utilizaron tambien se desactivan
      if(chbAmox.isSelected()){
          //SI SE SELECCIONO EL CHECKBOX Y NO SE RELLENO LA CAJA DE TEXTO, PEDIRA QUE RELLENE EL CAMPO NECESARIO 
          if(CAmox.getText().length()==0){
              JOptionPane.showMessageDialog(null,"Rellena el campo 'Cantidad' de la primera fila o desmarque la opción");
            }
      }else{chbAmox.setEnabled(false);CAmox.setEnabled(false);CAmox.setText("0.0");SAmox.setEnabled(false);SAmox.setText("0.0");lblAmox.setEnabled(false);}
      if(chbIbu.isSelected()){
          //SI SE SELECCIONO EL CHECKBOX Y NO SE RELLENO LA CAJA DE TEXTO, PEDIRA QUE RELLENE EL CAMPO NECESARIO 
           if(CIbu.getText().length()==0){
               JOptionPane.showMessageDialog(null,"Rellena el campo 'Cantidad' de la segunda fila o desmarque la opción");
            }
      }else{chbIbu.setEnabled(false);CIbu.setEnabled(false);SIbu.setEnabled(false);CIbu.setText("0.0");SIbu.setText("0.0");lblIbu.setEnabled(false);}
      if(chbAnta.isSelected()){
          //SI SE SELECCIONO EL CHECKBOX Y NO SE RELLENO LA CAJA DE TEXTO, PEDIRA QUE RELLENE EL CAMPO NECESARIO 
           if(CAnta.getText().length()==0){
               JOptionPane.showMessageDialog(null,"Rellena el campo 'Cantidad' de la tercera fila o desmarque la opción");
            }
      }else{chbAnta.setEnabled(false);CAnta.setEnabled(false);SAnta.setEnabled(false);lblAnta.setEnabled(false);CAnta.setText("0.0");SAnta.setText("0.0");}
       if(chbPeni.isSelected()){
           //SI SE SELECCIONO EL CHECKBOX Y NO SE RELLENO LA CAJA DE TEXTO, PEDIRA QUE RELLENE EL CAMPO NECESARIO 
           if(CPeni.getText().length()==0){
               JOptionPane.showMessageDialog(null,"Rellena el campo 'Cantidad' de la cuarta fila o desmarque la opción");
            }
       }else{chbPeni.setEnabled(false);CPeni.setEnabled(false);SPeni.setEnabled(false);lblPeni.setEnabled(false);CPeni.setText("0.0");SPeni.setText("0.0");}
       
       //Operacion Importe Parcial
       double suma;
       double s1=Double.parseDouble(SAmox.getText());
       double s2=Double.parseDouble(SIbu.getText());
       double s3=Double.parseDouble(SAnta.getText());
       double s4=Double.parseDouble(SPeni.getText());
       
       suma=s1+s2+s3+s4;
       timporte.setText(Double.toString(suma));
    
       //Descuento 
       String des=timporte.getText();
       double d1=Double.parseDouble(des)*0/100;
       double d2=Double.parseDouble(des)*8/100;
       double d3=Double.parseDouble(des)*10/100;
       double d4=Double.parseDouble(des)*15/100;
       double d5=Double.parseDouble(des)*20/100;
       double de=Double.parseDouble(des);
       if (de<=50){descuento.setText(Double.toString(d1));}
       if((de>=51) && (de<=200)){descuento.setText(Double.toString(d2));}
       if((de>=201) && (de<=250)){descuento.setText(Double.toString(d3));}
       if((de>=251) && (de<=300)){descuento.setText(Double.toString(d4));}
       if(de>=300){descuento.setText(Double.toString(d5));}
       
       //Total a PAGAR
       double res=Double.parseDouble(descuento.getText());
       double tp=de-res; 
       tpagar.setText(Double.toString(tp));
       
      
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void chbAmoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbAmoxActionPerformed
        //Al seleccionar el checkbok el cursor se posiciona en la caja de texto de Cantidad
        if (chbAmox.isSelected()){
            CAmox.requestFocus();
        } 
        else{CAmox.setText("");SAmox.setText("");}
                    
    }//GEN-LAST:event_chbAmoxActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //Al presionar el boton salir, primero te preguntara si quieres salir del programa o mantenerte ahi
        String botones[]={"SI","NO"};
        int eleccion=JOptionPane.showOptionDialog(this,"¿Desea salir del programa?","Titulo",0,0,null,botones,this);
        if (eleccion==JOptionPane.YES_OPTION){
         System.exit(0);
        }else if(eleccion==JOptionPane.NO_OPTION){
        }
       
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       //Activar lo que se habia desabilitado
       chbAmox.setEnabled(true);CAmox.setEnabled(true);SAmox.setEnabled(true);lblAmox.setEnabled(true);
       chbIbu.setEnabled(true);CIbu.setEnabled(true);SIbu.setEnabled(true);lblIbu.setEnabled(true);
       chbAnta.setEnabled(true);CAnta.setEnabled(true);SAnta.setEnabled(true);lblAnta.setEnabled(true);
       chbPeni.setEnabled(true);CPeni.setEnabled(true);SPeni.setEnabled(true);lblPeni.setEnabled(true);
       //Limpiar las cajas de texto
       CAmox.setText("");CIbu.setText("");CAnta.setText("");CPeni.setText("");
       SAmox.setText("");SIbu.setText("");SAnta.setText("");SPeni.setText("");
       timporte.setText("");tpagar.setText("");descuento.setText("");
       //Limpiar los checkbox
       if(chbAmox.isSelected()){chbAmox.setSelected(false);}
       if(chbIbu.isSelected()){chbIbu.setSelected(false);}
       if(chbAnta.isSelected()){chbAnta.setSelected(false);}
       if(chbPeni.isSelected()){chbPeni.setSelected(false);}
       
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void chbIbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIbuActionPerformed
        //Al seleccionar el checkbok el cursor se posiciona en la caja de texto de Cantidad
        if (chbIbu.isSelected()){
            CIbu.requestFocus();
        }else{CIbu.setText("");SIbu.setText("");}
    }//GEN-LAST:event_chbIbuActionPerformed

    private void chbAntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbAntaActionPerformed
        //Al seleccionar el checkbok el cursor se posiciona en la caja de texto de Cantidad
        if (chbAnta.isSelected()){
            CAnta.requestFocus();
        }else{CAnta.setText("");SAnta.setText("");}
    }//GEN-LAST:event_chbAntaActionPerformed

    private void chbPeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbPeniActionPerformed
        //Al seleccionar el checkbok el cursor se posiciona en la caja de texto de Cantidad
        if (chbPeni.isSelected()){
            CPeni.requestFocus();
        }else{CPeni.setText("");SPeni.setText("");}
    }//GEN-LAST:event_chbPeniActionPerformed

    private void SAmoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SAmoxKeyReleased
        
    }//GEN-LAST:event_SAmoxKeyReleased

    private void CAmoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAmoxActionPerformed
        
    }//GEN-LAST:event_CAmoxActionPerformed

    private void CAmoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CAmoxKeyReleased
        //hacer que automaticamente al ingresar la cantidad se rellene el subtotal
        double s1=80;
        double c1=Double.parseDouble(CAmox.getText());
        double t1=c1*s1;
        SAmox.setText(Double.toString(t1));
    }//GEN-LAST:event_CAmoxKeyReleased

    private void CIbuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CIbuKeyReleased
        //hacer que automaticamente al ingresar la cantidad se rellene el subtotal 
        double s1=50;
        double c1=Double.parseDouble(CIbu.getText());
        double t1=c1*s1;
        SIbu.setText(Double.toString(t1));
    }//GEN-LAST:event_CIbuKeyReleased

    private void CAntaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CAntaKeyReleased
        //hacer que automaticamente al ingresar la cantidad se rellene el subtotal
        double s1=65;
        double c1=Double.parseDouble(CAnta.getText());
        double t1=c1*s1;
        SAnta.setText(Double.toString(t1));
    }//GEN-LAST:event_CAntaKeyReleased

    private void CPeniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPeniKeyReleased
        //hacer que automaticamente al ingresar la cantidad se rellene el subtotal
        double s1=40;
        double c1=Double.parseDouble(CPeni.getText());
        double t1=c1*s1;
        SPeni.setText(Double.toString(t1));
    }//GEN-LAST:event_CPeniKeyReleased

    private void tpagarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpagarKeyReleased
     
        
    }//GEN-LAST:event_tpagarKeyReleased

    private void descuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descuentoActionPerformed

    private void descuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descuentoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_descuentoKeyReleased

    private void SIbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIbuActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_SIbuActionPerformed

    private void SAntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAntaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SAntaActionPerformed

    private void SPeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPeniActionPerformed
        
    }//GEN-LAST:event_SPeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(farma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(farma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(farma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(farma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new farma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CAmox;
    private javax.swing.JTextField CAnta;
    private javax.swing.JTextField CIbu;
    private javax.swing.JTextField CPeni;
    private javax.swing.JTextField SAmox;
    private javax.swing.JTextField SAnta;
    private javax.swing.JTextField SIbu;
    private javax.swing.JTextField SPeni;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chbAmox;
    private javax.swing.JCheckBox chbAnta;
    private javax.swing.JCheckBox chbIbu;
    private javax.swing.JCheckBox chbPeni;
    private javax.swing.JTextField descuento;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblAmox;
    private javax.swing.JLabel lblAnta;
    private javax.swing.JLabel lblIbu;
    private javax.swing.JLabel lblPeni;
    private javax.swing.JTextField timporte;
    private javax.swing.JTextField tpagar;
    // End of variables declaration//GEN-END:variables
}
